### ISSUE TITLE
Horizontal scroll on small screen

### ISSUE THREAD

**Issue by eatonmunoz** [AndiDittrich/WordPress.Enlighter#31]
How about horizontal scroll on small screen like mobile browser for long code instead of line wrapping? Is there a way to enable it or not supported yet? I think I need this feature. Thank you.

**Comment by AndiDittrich** [comment]
Hi eatonmunoz,

you can prevent the word-wrap by adding the following lines to your themes css file (styles.css) -  it will override the default behaviour:

**Code**

```css
.EnlighterJS{
   width: auto !important;
   overflow-x: scroll !important;
   word-wrap: normal !important;
}
.EnlighterJS li{
  white-space: pre !important;
}
```

**Result**
![enlighter_scrollbar](https://cloud.githubusercontent.com/assets/1474107/14043969/d5eddc14-f28a-11e5-8763-23e747b35817.jpg)

**Media Query**
Additionally, you can wrap the code into a [css media query](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) to enable scrolling only on small devices:

```less
@media only screen 
  and (min-device-width: 320px) 
  and (max-device-width: 480px){

.EnlighterJS{
   width: auto !important;
   overflow-x: scroll !important;
   word-wrap: normal !important;
}
.EnlighterJS li{
  white-space: pre !important;
}
}
```

best regards, Andi

**Comment by eatonmunoz** [comment]
Great, actually that's what I want. I wonder if it could be horizontal-scrollable by default without modifying the css, or maybe there is another consideration? 

Anyway thank you for this nice and helpful plugin.

Best regards,
Eaton Munoz.

**Comment by bjorntheart** [comment]
Hey Andi.

I tried the CSS you provided in the example, but when I scroll horizontally there is an issue with the background color

<img width="712" alt="screen shot 2016-06-12 at 16 30 48" src="https://cloud.githubusercontent.com/assets/53244/15991706/2b03a008-30bb-11e6-9fe0-e1f3931d4c7a.png">

**Comment by AndiDittrich** [comment]
Dear Bjron,

currently this is not easy to fix: it is caused by the different colors of the `ul` as well as `li` containers (to get a different line-number-bar background-color).

You can modify the CSS to set the line-number background color to the same value like the code background or maybe use a background image element.

**Comment by Drophax** [comment]
Nice Great, actually that's what I search. In future wordpress plugin its need a check box for aktiv scrollbar or not.

**Comment by indikatordesign** [comment]
Hi Andi,

at first thanks for this great plugin. Found it yesterday and it seems to work very well.

I added your shared snippet from above to my stylesheet. Unfortunately, the horizontal scroll does not work for me: [example-link](https://indikator-design.com/how-to-move-wordpress/). Any idea how to fix it?

Thank you and best regards, Bruno

**Comment by AndiDittrich** [comment]
Hi Bruno,
it seems to work fine ?! whats your issue ?

br, Andi

**Comment by indikatordesign** [comment]
It works in Safari and Firefox on a Mac.

But not in Chrome and Opera. Here it is fixed with the behavior of overflow:hidden.

**Comment by AndiDittrich** [comment]
your example works fine on chrome(win10). only the background issue is still present

**Comment by indikatordesign** [comment]
Hm, it should be very easy to fix the background.

But it seems that the overflow-problem is Mac-related: [example](https://indikator-design.de/medien/issues/enlighter-scroll-x-mac.mp4)

**Comment by JavierSegoviaCordoba** [comment]
In my case I solved the @bjorntheart problem with this:
```
.EnlighterJS {
         width: auto !important;
         overflow-x: auto !important;
         word-wrap: normal !important;
}

ul.EnlighterJS{
	 display: grid;
}

.EnlighterJS li{
        white-space: pre !important;
	display: table-caption;
}
```

**Comment by nikolauskrismer** [comment]
The background issue is not resolved...
... when using line numbers "ol.EnlighterJS" needs to be added and "display: table-caption" seems to hide line numbers in that case.

So for me the correct CSS seems to be (tested in Fedora 28 with Firefox 62 and the classic theme):
```
.EnlighterJS {
	width: auto;
	overflow-x: auto;
	word-wrap: normal;
}

ol.EnlighterJS,
ul.EnlighterJS {
	display: table;
}

.EnlighterJS li {
	white-space: pre;
}
```

**Comment by AndiDittrich** [comment]
**Just FYI**

i've added a dedicated option to EnlighterJS v3 which allows to choose between the overflow modes `scroll` and `wrap`. it will be available in Enlighter v4 soon (the css solution is not backward compatble!)

```js
var options = {
        language : 'javascript',
        theme: 'enlighter',
        indent : 2,
        linenumbers: true,
        linehover: true,
        textOverflow: 'scroll'
};
```

**Comment by SKozak** [comment]
> The background issue is not resolved...
> ... when using line numbers "ol.EnlighterJS" needs to be added and "display: table-caption" seems to hide line numbers in that case.
> 
> So for me the correct CSS seems to be (tested in Fedora 28 with Firefox 62 and the classic theme):
> 
> ```
> .EnlighterJS {
> 	width: auto;
> 	overflow-x: auto;
> 	word-wrap: normal;
> }
> 
> ol.EnlighterJS,
> ul.EnlighterJS {
> 	display: grid;
> }
> 
> .EnlighterJS li {
> 	white-space: pre;
> }
> ```

Works for me

**Comment by Suplanus** [comment]
The fix from @nikolauskrismer works. But only on post page... not in the post overview page: [Example](https://suplanus.de/blog/)

**Comment by andreszs** [comment]
@AndiDittrich this option is not yet implemented in version 3.10.0, right? It would be nice to have it because line wrapping looks very bad for certain code samples.

**Comment by AndiDittrich** [comment]
@andreszs 

it has been added to EnlighterJS v3 - but this version cannot be added to the current WordPress plugin - the next major release (Enlighter v4) will include this option...

in the meantime you can use the experimental integration and override the settings manually (see experiments repo)

**Comment by Suplanus** [comment]
I tested it on v4 Beta 1 Wordpress Plugin.
But the problem is still there. Look [here](https://suplanus.de/blog/page/2/).

**Comment by AndiDittrich** [comment]
@Suplanus 

the issue seems to be related to your theme...please check the layout

**testing env**

![image](https://user-images.githubusercontent.com/1474107/61623801-ab81b180-ac77-11e9-917c-39341de4afcc.png)

**Comment by Suplanus** [comment]
Thank you that you looked on an issue on my side (& site 🦄).

I am not that CSS-Guy, but I think it should be fixed with custom CSS:

```css
.enlighter-overflow-scroll.enlighter-v-standard {
    display: grid !important;
}
```

**Comment by Suplanus** [comment]
... but don't work in Safari 🤦‍♂ 
Have you a tip for me?

**Comment by AndiDittrich** [comment]
take a look onto the css rules i've disabled in the post above. your css fix looks weak...

**Comment by Suplanus** [comment]
This works in Safari & Chrome 🤦‍♂ 👍 

```css
.fusion-blog-layout-medium .fusion-post-medium, .fusion-blog-layout-medium .fusion-post-medium-alternate, .fusion-blog-layout-medium-alternate .fusion-post-medium, .fusion-blog-layout-medium-alternate .fusion-post-medium-alternate {
    display: block !important;
}
.enlighter-overflow-scroll.enlighter-v-standard {
    display: grid !important;
}
```

**Comment by AndiDittrich** [comment]
`display: grid`shouldn't be necessary

**Comment by Suplanus** [comment]
Chrome need this property, don't know why 🤣

**Comment by ebody** [comment]
I use the theme "Twenty Sixteen" and use the Enlighter Plugin Version 3.10.0 enable for the "Gutenberg Editor".
I can´t find a [textOverflow Option](https://github.com/EnlighterJS/Plugin.WordPress/issues/31#issuecomment-421071228) in the settings or if i edit an article.

**Is it my mistake, a template or gutenberg issue or a bug?**

**Comment by AndiDittrich** [comment]
you need Enlighter v4-beta1

**Comment by softtama** [comment]
Hi! Is horizontal scrolling already a feature in current release version of Enlighter WordPress?

**Comment by AndiDittrich** [comment]
of course. `Enlighter -> Appearance`

**Comment by swtestacademy** [comment]
Text overflow (scroll bar) option is not working fine anymore: https://www.swtestacademy.com/datepicker-using-selenium/ I have tested it 14 inch MacBook pro on chrome.

**Comment by AndiDittrich** [comment]
@swtestacademy your codeblocks doesn't have the attribute `enlighter-overflow-scroll` set - maybe it's a caching issue (EnlighterJS js config) or some custom css. the recent EnlighterJS version changed it's internal dom structure - the external API kept untouched but this may break custom modifictions - in this case you have to take care of such changes on your own

**Comment by swtestacademy** [comment]
I disabled the scroll bar maybe because of that you could not see the enlighter-overflow-scroll attribute. I also removed all customizations and still I am facing an issue. I will debug more and if I find anything, I will post here.

**Comment by swtestacademy** [comment]
I will leave the scroll bar option enabled like below:

class="enlighter-default enlighter-v-standard enlighter-t-wpcustom enlighter-overflow-scroll "

if you have a chance, would you re-check again?

**Comment by swtestacademy** [comment]
It is about the "Dynamic Resource Invocation (DRI)" option. When I disable it, the scroll bar comes, but the colors and theme have gone this time, and the code blocks turn to full grey mode. I am trying to understand why this is happening, but I found a point to narrow down the problem area.

**Comment by swtestacademy** [comment]
@AndiDittrich, I have finally solved the issue.

**Solution steps:**

1) I disabled the Dynamic Resource Invocation (DRI).
2) I selected the Initialization code as " Add code to the library (single file).

After these changes, the scroll bar appeared.
