### ISSUE TITLE
Underscores in XML

### ISSUE THREAD

**Issue by higginbg** [AndiDittrich/WordPress.Enlighter#72]
Hello,

It appears that underscores mess up the formatting in XML.  Here is the code:
```xml
    <lesson>
        <title>Hindsight is 20/20</title>
        <grade target="5" lowerbound="3" upperbound="6"/>
        <time total="50" unit="minutes"/>
        <lesson_cost amount="0" unit="USDollars"/>
        <summary>Students measure their eyesight and learn how lenses can enhance eyesight`
        </summary>
        <keywords>
            <keyword>eyesight</keyword>
            <keyword>vision</keyword>
            <keyword>20/20</keyword>
        </keywords>
        <edu_standards>
            <edu_standard identifier="14000"/>
            <edu_standard identifier="14011"/>
        </edu_standards>
        <lesson_body>With our eyes we see the world around us. Having two eyes helps us see a larger area than just one eye and with two eyes we can... etc. etc.
        </lesson_body>
        <copyright owner="We, the legal owners of this document" year="2016" />
    </lesson>
```
And a screenshot:

![capture](https://user-images.githubusercontent.com/30296062/28377027-78bc52d6-6c60-11e7-8761-b5d99f9ccd06.PNG)

Any ideas for a fix?

**Comment by AndiDittrich** [comment]
Hi
thanks for your report! it was a bug within EnlighterJS XML tokenizer/highlighting rules. it is fixed within the current release **v2.11.1**

Example: https://enlighterjs.org/Language.XML.html

br, Andi

**Comment by AndiDittrich** [comment]
Updated EnlighterJS package to v2.11.1

**Comment by higginbg** [comment]
Thanks for the quick reply!

Is this true for the WordPress plugin?  I have Enlighter Version 3.4 on WordPress (which I believe is most current), but it's still having this issue.

**Comment by AndiDittrich** [comment]
3.5 is not released yet ;) please use the master branch on GitHub
